name: Despliegue AWS Lambda

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Instalar Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Ejecutar pruebas unitarias
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-2
        ENV: PROD
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      run: go test ./...

    - name: Ejecutar script de despliegue para prod
      run: bash release.sh prod

  deploy-to-stage:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Instalar Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Ejecutar pruebas unitarias
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-2
        ENV: DEV
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      run: go test ./...

    - name: Ejecutar script de despliegue para stage
      run: bash release.sh stage
